### ISSUE TITLE
slower than python

### ISSUE THREAD

**Issue by cookernetes** [ecp-lang/ecp-interpreter#16]
oh my god why the hell is this slower than python?

this is so annoyingI just want to dvelop games with the unity engine with my favourite language ecp!

omg.

**Comment by Conqu3red** [comment]
Hey there, this implementation parses your ECP source code, during this process it is transformed into a Python Abstract Syntax Tree which is then given to the python interpreter to be executed. Apart from this initial transpilation overhead, it should run at the same speed as if you wrote the python code to do the same thing (this code can be displayed using command line flags)

**Comment by cookernetes** [comment]
but python is still slow - why use python when you can use the best programming language, cobol?

**Comment by deadhash** [comment]
+ ratio
